<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Category A: Latihan Hari Senin - Jumat (08.00 - 16.00 WIB)
        // Manual Packages
        DB::table('courses')->insert([
            [
                'name' => 'Paket A1',
                'description' => 'Paket latihan mengemudi mobil Manual 5 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Ideal untuk pemula yang ingin belajar dasar-dasar mengemudi dengan kendaraan transmisi manual.',
                'category' => 'manual',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 5,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 800000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket A2',
                'description' => 'Paket latihan mengemudi mobil Manual 7 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Pilihan tepat untuk pemula yang membutuhkan waktu latihan lebih banyak dengan transmisi manual.',
                'category' => 'manual',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 7,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 950000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket A3',
                'description' => 'Paket latihan mengemudi mobil Manual 10 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Memberikan pengalaman mengemudi yang lebih intensif untuk pemula maupun yang ingin mengasah keterampilan.',
                'category' => 'manual',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 10,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1300000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket A4',
                'description' => 'Paket latihan mengemudi mobil Manual 12 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Komprehensif untuk pemula hingga tingkat menengah dengan waktu latihan yang cukup panjang.',
                'category' => 'manual',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 12,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1500000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket A5',
                'description' => 'Paket latihan mengemudi mobil Manual 15 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Paket lengkap untuk menguasai berbagai teknik mengemudi dengan transmisi manual secara mendalam.',
                'category' => 'manual',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 15,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1825000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Matic Packages
        DB::table('courses')->insert([
            [
                'name' => 'Paket A6',
                'description' => 'Paket latihan mengemudi mobil Matic 6 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Ideal untuk yang ingin belajar dasar-dasar mengemudi dengan kendaraan transmisi otomatis.',
                'category' => 'matic',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'matic',
                'session' => 6,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 950000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket A7',
                'description' => 'Paket latihan mengemudi mobil Matic 8 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Pilihan tepat untuk pemula yang membutuhkan waktu latihan lebih banyak dengan transmisi otomatis.',
                'category' => 'matic',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'matic',
                'session' => 8,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1050000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket A8',
                'description' => 'Paket latihan mengemudi mobil Matic 12 hari selama 1 jam per sesi di hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Komprehensif untuk pemula hingga tingkat menengah dengan waktu latihan yang cukup panjang menggunakan transmisi otomatis.',
                'category' => 'matic',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'matic',
                'session' => 12,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1790000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Category B: Latihan Hari Minggu / Hari Libur / Jam Lembur (06/07/17/18 WIB)
        DB::table('courses')->insert([
            [
                'name' => 'Paket B1',
                'description' => 'Paket latihan mengemudi mobil Manual 3 hari selama 2 jam per sesi di hari Minggu/Libur atau jam lembur (06/07/17/18 WIB). Ideal untuk yang memiliki kesibukan di hari kerja dan hanya bisa berlatih di akhir pekan.',
                'category' => 'manual',
                'days' => 'sunday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 3,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 900000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket B2',
                'description' => 'Paket latihan mengemudi mobil Manual 5 hari selama 2 jam per sesi di hari Minggu/Libur atau jam lembur (06/07/17/18 WIB). Memberikan waktu latihan yang lebih panjang di akhir pekan untuk penguasaan keterampilan yang lebih baik.',
                'category' => 'manual',
                'days' => 'sunday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 5,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1500000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket B3',
                'description' => 'Paket latihan mengemudi mobil Manual 8 hari selama 2 jam per sesi di hari Minggu/Libur atau jam lembur (06/07/17/18 WIB). Paket intensif untuk penguasaan keterampilan mengemudi secara komprehensif di hari libur.',
                'category' => 'manual',
                'days' => 'sunday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 8,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 2300000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket B4',
                'description' => 'Paket latihan mengemudi mobil Matic 3 hari selama 2 jam per sesi di hari Minggu/Libur atau jam lembur (06/07/17/18 WIB). Solusi praktis untuk belajar mengemudi transmisi otomatis di akhir pekan.',
                'category' => 'matic',
                'days' => 'sunday',
                'default_car' => 1,
                'default_car_type' => 'matic',
                'session' => 3,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1000000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket B5',
                'description' => 'Paket latihan mengemudi mobil Matic 5 hari selama 2 jam per sesi di hari Minggu/Libur atau jam lembur (06/07/17/18 WIB). Memberikan waktu latihan yang lebih panjang di akhir pekan untuk penguasaan keterampilan mengemudi mobil otomatis.',
                'category' => 'matic',
                'days' => 'sunday',
                'default_car' => 1,
                'default_car_type' => 'matic',
                'session' => 5,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1600000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket B6',
                'description' => 'Paket latihan mengemudi mobil Matic 8 hari selama 2 jam per sesi di hari Minggu/Libur atau jam lembur (06/07/17/18 WIB). Paket intensif untuk penguasaan keterampilan mengemudi transmisi otomatis secara komprehensif di hari libur.',
                'category' => 'matic',
                'days' => 'sunday',
                'default_car' => 1,
                'default_car_type' => 'matic',
                'session' => 8,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 2400000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Category C: Paket Kombinasi Manual + Automatic (MT + AT)
        DB::table('courses')->insert([
            [
                'name' => 'Paket C1',
                'description' => 'Paket kombinasi latihan mengemudi 3 hari mobil Manual + 2 jam mobil Matic di hari kerja (Senin-Jumat). Ideal untuk yang ingin menguasai kedua jenis transmisi dengan fokus utama pada kendaraan manual.',
                'category' => 'combine',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 3,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 900000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket C2',
                'description' => 'Paket kombinasi latihan mengemudi 5 hari mobil Manual + 3 jam mobil Matic di hari kerja (Senin-Jumat). Memberikan pengalaman yang seimbang untuk kedua jenis transmisi dengan porsi waktu yang lebih banyak.',
                'category' => 'combine',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 5,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1300000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket C3',
                'description' => 'Paket kombinasi latihan mengemudi 8 hari mobil Manual + 4 jam mobil Matic di hari kerja (Senin-Jumat). Paket lengkap untuk menguasai kedua jenis transmisi dengan fokus mendalam pada keterampilan mengemudi manual dan tambahan pengalaman untuk mobil otomatis.',
                'category' => 'combine',
                'days' => 'weekday',
                'default_car' => 1,
                'default_car_type' => 'manual',
                'session' => 8,
                'duration_session' => 'month',
                'duration' => 1,
                'price' => 1700000,
                'expired' => '2030-12-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
